### ISSUE TITLE
Creating a live maze-solver 

### ISSUE THREAD

**Issue by Jam-Burger** [Mrinank-Bhowmick/python-beginner-projects#117]
Make a maze-solver using 2 different approaches
1.  normal method(iterative)
2.  A* Path-finding algorithm

**Comment by Jam-Burger** [comment]
> Make a maze-solver using 2 different approaches
> 
> 1. normal method(iterative)
> 2. A* Path-finding algorithm

can you assign me this issue under Hactoberfest?

**Comment by Mrinank-Bhowmick** [comment]
@Jam-Burger Want to contribute now?
