### ISSUE TITLE
Encode-Decode in python

### ISSUE THREAD

**Issue by glacias07** [Mrinank-Bhowmick/python-beginner-projects#118]
**Is your feature request related to a problem? Please describe.**
Sending plain text containing password over internet can be risky. So an encrypter with multiple ciphers would be a great idea.

**Describe the solution you'd like**
One program comprising of multiple ciphers with encoding as well as decoding. Can also add an option to bruteforce with all ciphers if it is unknown which cipher was used to encode.

**Describe alternatives you've considered**
I have been using cyber chef for a long time and it is a very handy tool when doing CTF's. But there are certain things I wished were there in it that would have made my work simpler.

**Comment by Mrinank-Bhowmick** [comment]
Cool thing to do

**Comment by Mrinank-Bhowmick** [comment]
closing it for now, if you want to contribute reopen this again
