### ISSUE TITLE
Auto complete feature

### ISSUE THREAD

**Issue by nagarajan-ck** [Mrinank-Bhowmick/python-beginner-projects#122]
Tries are often used to implement auto complete, objective is to have a script that lists all the possible words from a list for a specific input.

**Comment by Mrinank-Bhowmick** [comment]
Not related to development

**Comment by 0xYashwanth** [comment]
Hey @Mrinank-Bhowmick, I have a pretty decent knowledge of Python, and I want to contribute to the Auto Complete project.
Could you please assign this to me?
Thanks for reading!
