### ISSUE TITLE
QRCode Scanner

### ISSUE THREAD

**Issue by Logadheep** [Mrinank-Bhowmick/python-beginner-projects#125]
**Is your feature request related to a problem? Please describe.**
It would be annoying when you have to use the desktop for some link but the link is present as qrcode stored in mobile or any other external formats.

**Describe the solution you'd like**
I would like to add a project, more specifically script that could scan qrcodes from images or webcam

**Comment by Mrinank-Bhowmick** [comment]
Looks cool , go for it 👍

**Comment by Mrinank-Bhowmick** [comment]
merged
