### ISSUE TITLE
Credentials should always be read from environment variables

### ISSUE THREAD

**Issue by anushds** [Mrinank-Bhowmick/python-beginner-projects#134]
In this script, the email credentials should be read from environment variables and should not be mentioned explicitly in code as it is done here https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Send-Email

**Comment by anushds** [comment]
@Mrinank-Bhowmick Please assign this issue to me

**Comment by anushds** [comment]
@Mrinank-Bhowmick I've made appropriate changes in code for this issue. Please review and merge.
Here is the link for the PR: https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/151

**Comment by Mrinank-Bhowmick** [comment]
Merged
