### ISSUE TITLE
Twitter-Bot

### ISSUE THREAD

**Issue by harshhes** [Mrinank-Bhowmick/python-beginner-projects#135]
Twitter Bot which can Retweet the tweets which have a particular hashtag- #programming, #coding ,etc

**Comment by harshhes** [comment]
!assign

**Comment by Mrinank-Bhowmick** [comment]
Go for it 👍

**Comment by Mrinank-Bhowmick** [comment]
merged

**Comment by harshhes** [comment]
> merged

Hello, Can you please add the hacktoberfest label to it, the contribution didn't got count in my merged PRs
