### ISSUE TITLE
Youtube video downloader

### ISSUE THREAD

**Issue by harshhes** [Mrinank-Bhowmick/python-beginner-projects#136]
Youtube video downloader which can download any video with the highest resolution by just the url of that video, it can download even movies

**!assign** it to me

**Comment by Mrinank-Bhowmick** [comment]
Already exists : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/YouTube%20Video%20Downloader
you may add more features to it 👍

**Comment by harshhes** [comment]
> Already exists : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/YouTube%20Video%20Downloader you may add more features to it 👍

I saw the code, I can conclude that it's too long. I have 10 lines of code program

**Comment by Mrinank-Bhowmick** [comment]
> > Already exists : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/YouTube%20Video%20Downloader you may add more features to it 👍
> 
> I saw the code, I can conclude that it's too long. I have 10 lines of code program

Thats good but try to add more features to it

**Comment by 0xYashwanth** [comment]
Hey @Mrinank-Bhowmick, I have a pretty decent knowledge of Python, and I want to contribute to the Youtube video downloader project.
Could you please assign this to me?
Thanks for reading!

**Comment by Mrinank-Bhowmick** [comment]
> Hey @Mrinank-Bhowmick, I have a pretty decent knowledge of Python, and I want to contribute to the Youtube video downloader project. Could you please assign this to me? Thanks for reading!

Sure

**Comment by Mrinank-Bhowmick** [comment]
> Hey @Mrinank-Bhowmick, I have a pretty decent knowledge of Python, and I want to contribute to the Youtube video downloader project. Could you please assign this to me? Thanks for reading!

Make sure you add more features to the existing project

**Comment by 0xYashwanth** [comment]
Hey @Mrinank-Bhowmick, some of the features of the existing project are not working.
Should I make a whole new project with GUI using Tkinter?

**Comment by Mrinank-Bhowmick** [comment]
> Hey @Mrinank-Bhowmick, some of the features of the existing project are not working. Should I make a whole new project with GUI using Tkinter?

Sure

**Comment by Mrinank-Bhowmick** [comment]
New contributors are welcome, add new features to this existing project https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/YouTube%20Video%20Downloader

**Comment by parth-verma7** [comment]
@Mrinank-Bhowmick I would like to add one functionality. How about we transcribe it and then using GPT or Langchains or any other transformer we summarize it or we can create a question answering bot that can answer all questions related to the video.

**Comment by Mrinank-Bhowmick** [comment]
> @Mrinank-Bhowmick I would like to add one functionality. How about we transcribe it and then using GPT or Langchains or any other transformer we summarize it or we can create a question answering bot that can answer all questions related to the video.

Nice idea, make a pr if you are interested
