### ISSUE TITLE
Extend current password generator by allowing user to pick length of password

### ISSUE THREAD

**Issue by Josephtobi** [Mrinank-Bhowmick/python-beginner-projects#137]
add option to allow people pick the length of the password

**Comment by Josephtobi** [comment]
can i have a stab at this?

**Comment by Mrinank-Bhowmick** [comment]
Sure you can add more features to this project : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Password%20Generator

**Comment by 0xYashwanth** [comment]
Hey @Anjuli08, I have a pretty decent knowledge of Python, and I want to contribute to the Password Generator project.
Could you please assign this to me?
Thanks for reading!

**Comment by Mrinank-Bhowmick** [comment]
> Hey @Mrinank-Bhowmick , I have a pretty decent knowledge of Python, and I want to contribute to the Password Generator project. Could you please assign this to me? Thanks for reading!

Make your changes

**Comment by siddarthpai** [comment]
Hey, can I work on this?

**Comment by Mrinank-Bhowmick** [comment]
> Hey, can I work on this?
> 

Yeah yeah sure 👍
