### ISSUE TITLE
non-integers will give an error before the program terminates.

### ISSUE THREAD

**Issue by Guillotine189** [Mrinank-Bhowmick/python-beginner-projects#141]
**Is your feature request related to a problem? Please describe.**
If you do not enter a number but a string or a character ,the program shuts down with an error and it's really bad to see.

**Describe the solution you'd like**
adding some 'try except ' command such that it will end without an error that takes up half your screen, without changing any function.(🙂 )

**Describe alternatives you've considered**

**Additional context**
I am new to open source and contributing in general,sorry if i did something wrong.(I really didn't mean to..😔  )

This issue is related to the code in 
https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Rock_Paper_Scissors/main.py

**Comment by Guillotine189** [comment]
i would like you to assign this to me under hacktoberfest 2022

**Comment by Mrinank-Bhowmick** [comment]
sure go for it 👍
