### ISSUE TITLE
OTP GENERATOR

### ISSUE THREAD

**Issue by iamdestinychild** [Mrinank-Bhowmick/python-beginner-projects#144]
this is a python module that generates OTP codes for users in various format like only digits, digits and letters and so on

**Comment by iamdestinychild** [comment]
@Mrinank-Bhowmick please assign me this task

**Comment by Mrinank-Bhowmick** [comment]
sure go for it 👍

**Comment by iamdestinychild** [comment]
I have made a pull request on this issue @Mrinank-Bhowmick

**Comment by iamdestinychild** [comment]
https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/188

**Comment by Mrinank-Bhowmick** [comment]
Merged
