### ISSUE TITLE
Website Blocker.

### ISSUE THREAD

**Issue by Dhruvil-Lakhtaria** [Mrinank-Bhowmick/python-beginner-projects#152]
This is a real-world program that blocks certain distracting websites like Facebook, Youtube, etc during your work hours.
What we are going to do in this program is we will pass the link of websites that you think are distracting and the time that you are working on your computer and the program will block those websites.

We can have a common python script for a different host like mac, ubuntu and windows.
Once we have written the script we need to set it up according to the OS.
And we are done with the website blocker.

If this seems fine can you assign this to me.

**Comment by Dhruvil-Lakhtaria** [comment]
If you are assigning assign this under hacktober fest.

**Comment by Mrinank-Bhowmick** [comment]
Sure go for it 👍

**Comment by Dhruvil-Lakhtaria** [comment]
Made a PR #178

**Comment by Mrinank-Bhowmick** [comment]
Merged
