### ISSUE TITLE
Random Number Guessing Game

### ISSUE THREAD

**Issue by Ayan-09** [Mrinank-Bhowmick/python-beginner-projects#160]
Pls assign me this issue under the tag Hacktoberfest

**Comment by Mrinank-Bhowmick** [comment]
Already exists : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Guess%20Number
You may add more features to it 👍

**Comment by Targgus** [comment]
I'll add more features to this. Looks like an opportunity to remove some repetition and add some try/except.
