### ISSUE TITLE
Love Calculator 

### ISSUE THREAD

**Issue by piyushkdas0611** [Mrinank-Bhowmick/python-beginner-projects#165]
Write your name and their name, and the calculator returns the love score.. I would like to contribute on this..

**Comment by oriapp** [comment]
https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/170

**Comment by Mrinank-Bhowmick** [comment]
lets add more conditions 😹

**Comment by piyushkdas0611** [comment]
Do you remember there was a game caed Flame? Friends, love, affectionate, marriage enemy.. can add that too in the calculator..🥲

**Comment by Mrinank-Bhowmick** [comment]
yeah sure why not 👍
