### ISSUE TITLE
Project dirs

### ISSUE THREAD

**Issue by TechWiz-3** [Mrinank-Bhowmick/python-beginner-projects#176]
I think each project directory should also contain a `requirements.txt` for any dependencies and preferably also a `README.md` with one line about the functionality and a screenshot demonstrating what the project looks like.

Info for beginners on how to generate a `requirements.txt` can go in `CONTRIBUTING.md`

**Comment by TechWiz-3** [comment]
Also i reckon #3 can be pinned at the top so everyone can see it

**Comment by Mrinank-Bhowmick** [comment]
Ya sure people can add those

**Comment by kaustab28** [comment]
Hey @Mrinank-Bhowmick , I would like to work on this. Can you please assign it to me under hacktoberfest2023.
