### ISSUE TITLE
Face Detection using OpenCV.

### ISSUE THREAD

**Issue by RadhikaChhabra17** [Mrinank-Bhowmick/python-beginner-projects#177]
This project is detecting face in image and real time video. It uses OpenCV Library using your webcam as a primary camera. 
Can you assign this to me?

**Comment by Mrinank-Bhowmick** [comment]
Similar kind of project exists : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/facerecoginition
you may contribute to this
