### ISSUE TITLE
Enhancement of a "calculator" program in the project file

### ISSUE THREAD

**Issue by payallenka** [Mrinank-Bhowmick/python-beginner-projects#180]
I have been through your project file's calculator program. As I have noticed it doesn't have division function. I propose to add that function and to create a menu, example: 1 addition 2 subtraction so on; so the user can type 1 for activation of addition function and so on. 
I wish to participate in hacktoberfest. So if you accept my proposal then kindly assign me this task and add the hacktoberfest label to this.

**Comment by samarth777** [comment]
can you assign this to me

**Comment by Mrinank-Bhowmick** [comment]
> I have been through your project file's calculator program. As I have noticed it doesn't have division function. I propose to add that function and to create a menu, example: 1 addition 2 subtraction so on; so the user can type 1 for activation of addition function and so on. I wish to participate in hacktoberfest. So if you accept my proposal then kindly assign me this task and add the hacktoberfest label to this.

sure go for it 👍
