### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by iamdestinychild** [Mrinank-Bhowmick/python-beginner-projects#190]
A python game for beginners focusing on conditional statements and more

**Comment by sohail9972** [comment]
could you please assign it to me

**Comment by iamdestinychild** [comment]
I wanted to take this task that's why I created it.

**Comment by Mrinank-Bhowmick** [comment]
> A python game for beginners focusing on conditional statements and more

hey it already exists here : https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Rock_Paper_Scissors
you may contribute to this 👍
