### ISSUE TITLE
Adding AES256 Encryption/Decryption as a beginner friendly project

### ISSUE THREAD

**Issue by oyeanmol** [Mrinank-Bhowmick/python-beginner-projects#195]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Here is a demo of the working of AES256 encryption and decryption algrorithm
![Screenshot 2022-10-20 134838](https://user-images.githubusercontent.com/99896373/196895153-c0e40bb4-95e8-4d98-86bd-eb0f051c218a.png)

**Comment by Mrinank-Bhowmick** [comment]
Go for it 👍
