### ISSUE TITLE
Python Bill or Reciept generator

### ISSUE THREAD

**Issue by Subha-5** [Mrinank-Bhowmick/python-beginner-projects#199]
**Description**
A simple project to generate bills based on the inputs provided by the shopkeeper. 

***Note*** : This program will provide the customer the bill in pdf format

**Additional Info**
This project is in elementary stages and can be further improved.

**Comment by Subha-5** [comment]
@Mrinank-Bhowmick please assign me this issue

**Comment by Mrinank-Bhowmick** [comment]
Nice idea , go for it 👍

**Comment by Subha-5** [comment]
@Mrinank-Bhowmick please review the pr #211. In the readme, I have also added a demonstration video of the project. Be sure to check it out.
