### ISSUE TITLE
Basic Color detection using open CV

### ISSUE THREAD

**Issue by GigabyteZX1** [Mrinank-Bhowmick/python-beginner-projects#210]
The python script will allow user to detect basic color in live feed using their webcam or any other peripheral camera device connected to their pc. Can you assign it to me. I have already sent a PR regarding this issue.

**Comment by Mrinank-Bhowmick** [comment]
Can you please mention the pr link here

**Comment by Mrinank-Bhowmick** [comment]
no worries , merged
