### ISSUE TITLE
Update NumberGuessingApp

### ISSUE THREAD

**Issue by dab07** [Mrinank-Bhowmick/python-beginner-projects#221]
I found errors in NumberGuessingAPP inside Projects folder.
Can you please assign me to solve the errors and make the program more beginner friendly?

Thank You

**Comment by Mrinank-Bhowmick** [comment]
> I found errors in NumberGuessingAPP inside Projects folder. Can you please assign me to solve the errors and make the program more beginner friendly?
> 
> Thank You

sure 👍

**Comment by Mrinank-Bhowmick** [comment]
merged
