### ISSUE TITLE
Site Connectivity Checker

### ISSUE THREAD

**Issue by Subha-5** [Mrinank-Bhowmick/python-beginner-projects#222]
**Tech stack** : Python and some external modules
**Usage**: To test connnectivity of the provided website
**Input**: the website URL
**Output**: the response code and corresponding status of the website.

**Comment by Subha-5** [comment]
@Mrinank-Bhowmick please assign me this issue for hacktoberfest 2022

**Comment by Subha-5** [comment]
I will submit the associated pr within today only.

**Comment by Mrinank-Bhowmick** [comment]
> I will submit the associated pr within today only.

Sure ⏲️
