### ISSUE TITLE
New Cricket game

### ISSUE THREAD

**Issue by herepete** [Mrinank-Bhowmick/python-beginner-projects#270]
Hi,

I was going to do a re-write of HandCricket to make it more of a longer game.
Its going to move from a beginner project to more of an intermediate level.

Do you want me to upload it as a new project or would you rather i develop it separately in my own repo?

Kind Regards

Peter

**Comment by Mrinank-Bhowmick** [comment]
Can you make changes in the present file and make it more interactive and intermediate level?
File: https://github.com/Mrinank-Bhowmick/python-beginner-projects/blob/main/projects/HandCricket/main.py
