### ISSUE TITLE
Web page 

### ISSUE THREAD

**Issue by Madhugangwar109** [Mrinank-Bhowmick/python-beginner-projects#282]
<!DocType html>
<html>
<body>
  <form>
 <h1> Contact with us </h1>
  <p> here we feed to you  fill the question s for contact with us </p>
   <label> Name </label><br>
     <input></label><br><br>
     
       <label> Phone no</label><br>
  <input> </label><br><br>
  
       <label>E-mail ID </label><br>
         <input></label><br><br>
         
       <label>Subject </label><br>
        <select subject=" ">
      <option value="English">English </option>
     
    <option value="Hindi">Hindi </option>
  <option value ="punjabi">punjabi</option>   
       </select><br><br>
       <label>Gender<label><br>
         <select Gender="">
   <option value = "Male">Male</option>
   <option value = "Female"female</option>
   </select><br><br>
    <input type ="submit"="send"><br><br>
   
    
        </form>
      </body>
     </html>

**Comment by Mrinank-Bhowmick** [comment]
Add some projects related to python


> # Contact with us
> here we feed to you fill the question s for contact with us
> 
> Name
> 
> 
> ```
>    <label> Phone no</label><br>
> ```
> 
> ```
>    <label>E-mail ID </label><br>
>      <input></label><br><br>
>      
>    <label>Subject </label><br>
>     <select subject=" ">
>   <option value="English">English </option>
>  
> <option value="Hindi">Hindi </option>
> ```
> 
> punjabi
> 
> Gender
> Male
> 
> 
> 
> ```
>     </form>
>   </body>
>  </html>
> ```
