### ISSUE TITLE
Create a video subtitle generator program

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [Mrinank-Bhowmick/python-beginner-projects#305]
### Description:
This program should take a video file as input and generate a subtitle file (.srt) as output. The subtitle file should contain the timestamps and the transcribed text of the audio in the video. The program should also be able to handle different languages and accents.

### Requirements:
Currently we are using [openai wisper](https://github.com/openai/whisper) model.

### Features to be added
* User driven menu has to be improved where user can choose in which language they need to get the translation.
* Multiple output formats should be added like json,text etc , currently its giving srt format output.   
* User can choose other models also in menu to get best results.
* Suggest more ...

**Comment by Mrinank-Bhowmick** [comment]
_This is an **open issue** for all_, 
you can make changes in the existing folder https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Video-subtitle-generator

**Comment by ArifShariar** [comment]
Hello @Mrinank-Bhowmick 
I have added the required changes in the proposed pull request. Please check them
