### ISSUE TITLE
Adding some feature in Audiobooks

### ISSUE THREAD

**Issue by ayan-joshi** [Mrinank-Bhowmick/python-beginner-projects#312]
**Is your feature request related to a problem? Please describe.**
adding a command-line argument to specify the PDF file to read.

**Describe the solution you'd like**
This can make the script more versatile and user-friendly. 
This addition makes your script more flexible and user-friendly by allowing users to specify the PDF file they want to read as a command-line argument.

**Describe alternatives you've considered**

**Additional context**
I'm practicing for the hacktoberfest , so let me solve this issue

**Comment by Mrinank-Bhowmick** [comment]
Hey @ayan-joshi ,
I liked your idea , go for it 🚀

**Comment by Mrinank-Bhowmick** [comment]
Merged 👍
