### ISSUE TITLE
Request for Contributions: Projects Utilizing ChatGPT API

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [Mrinank-Bhowmick/python-beginner-projects#313]
Hello everyone 🤝 ,

We are excited to announce that we are looking for contributors to our repository who can create innovative projects using the ChatGPT API. This is a great opportunity to explore the capabilities of the ChatGPT model and integrate it into a variety of applications.

The goal is to create projects that leverage the conversational abilities of ChatGPT to provide value in different domains. This could be anything from a chatbot for customer service, a virtual assistant for productivity apps, or even a storytelling bot for entertainment purposes.

We believe that the possibilities are endless and we can’t wait to see what you come up with. Your contributions will not only help enrich this repository but also provide learning resources for others in the community.

Please ensure that your project is beginner-friendly and includes clear instructions on how to use the ChatGPT API. Also, remember to follow all guidelines and best practices for using the API responsibly.

Looking forward to your innovative contributions!

**Comment by Mrinank-Bhowmick** [comment]
This issue will be open for everyone 🎸

**Comment by duraldo** [comment]
I'm really new at this, but this is the route I am going with my own project, kinda. (except using Rasa Open source), I don't know how to use the API yet. Whole reason I plan to work with Rasa is because I get it, then was going to go with the API. Who knows where this route will go. I think I will go the chatGPT API route when I get to that point now.

**Comment by Mrinank-Bhowmick** [comment]
> I'm really new at this, but this is the route I am going with my own project, kinda. (except using Rasa Open source), I don't know how to use the API yet. Whole reason I plan to work with Rasa is because I get it, then was going to go with the API. Who knows where this route will go. I think I will go the chatGPT API route when I get to that point now.

Ya sure @duraldo , you can try and make some small projects related to your idea and make a pr

**Comment by duraldo** [comment]
> Ya sure @duraldo , you can try and make some small projects related to your idea and make a pr


awesome! I still have no idea how this will work, it will just... happen. If anything, I can write a guide how to use the API that is beginner friendly. I kinda want to have a sarcastic/funny "Bonzi Buddy" type AI (without the malware), but has utility, for example, managing your system files. 

Simply: Personalized ChatGPT for simple tasks. I was reading it is possible to emulate ChatGPT using Rasa Open source (why I went that route originally).



I'm very new to github, so I apologize if I break rules or something by accident.

**Comment by Mrinank-Bhowmick** [comment]
> > Ya sure @duraldo , you can try and make some small projects related to your idea and make a pr
> 
> awesome! I still have no idea how this will work, it will just... happen. If anything, I can write a guide how to use the API that is beginner friendly. I kinda want to have a sarcastic/funny "Bonzi Buddy" type AI (without the malware), but has utility, for example, managing your system files.
> 
> Simply: Personalized ChatGPT for simple tasks. I was reading it is possible to emulate ChatGPT using Rasa Open source (why I went that route originally).
> 
> I'm very new to github, so I apologize if I break rules or something by accident.

You can give it a try and can choose any model, just make sure that you are making a separate folder like other's are doing [here](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects) and your program should be coded in **python** and the repo suggests.

**Comment by Mrinank-Bhowmick** [comment]
Keeping this issue open for everyone

**Comment by dikshant182004** [comment]
hii @Mrinank-Bhowmick .i have made a joke maker which can tell u joke by interacting with u by taking and giving output in a form of voice.I have not added any frontend  like things using this we can get jokes on any categories by just providing it .I have also taken care of error handling .If u want we can provide different type of voice instead of pyttsx3 using .plz do have a look and give me the feedback about it

**Comment by Paulie-Aditya** [comment]
I can do a simple voice assistant using gpt api
would that be accepted?

**Comment by shriyansh7** [comment]
Hey @Mrinank-Bhowmik Can I contribute a project which is basically a fun and interactive ChatGPT-powered virtual assistant that can do tasks like tell the weather information and jokes, and also a basic calculator?

**Comment by papichoolo** [comment]
Hello @Mrinank-Bhowmick! I want to create a text summarizer app using ChatGPT API (with streamlit as the frontend framework) would that be an acceptable project idea?

**Comment by harshkasat** [comment]
@Mrinank-Bhowmick I already worked on this using LangChain and SerAPI. I'm done, please take a look at it. #374
