### ISSUE TITLE
Add a PostgreSQL CRUD Example

### ISSUE THREAD

**Issue by newtoallofthis123** [Mrinank-Bhowmick/python-beginner-projects#316]
PostgreSQL is an excellent Database for CRUD operations

I want to develop a neat example with well documented comments for this.

I have previous experience with working with PostgreSQL in python for my projects ([1](https://github.com/newtoallofthis123/NoobPaste), [2](https://github.com/newtoallofthis123/shortpaw), [3](https://github.com/newtoallofthis123/dbview).)

Can I get assigned this issue?

**Comment by Mrinank-Bhowmick** [comment]
Yeah sure @newtoallofthis123 , go for it 
assigning it you 🚀

**Comment by newtoallofthis123** [comment]
Thanks ✨

Also, would you be so kind as to add the `hacktoberfest` label to this so that it helps in my hacktober fest journey

**Comment by newtoallofthis123** [comment]
Thanks ☺️

**Comment by Mrinank-Bhowmick** [comment]
Merged 👍

**Comment by newtoallofthis123** [comment]
Awesome! Thanks 😄
