### ISSUE TITLE
Expense Tracker Project

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [Mrinank-Bhowmick/python-beginner-projects#322]
## Project Description 📄

We are looking for contributors who can help us build an **Expense Tracker** using Python. The goal of this project is to create a system that can track income and expenses, and provide summaries and reports.

## Getting Started 🚀

1. Fork this repository
2. Clone the forked repository
3. Set up your environment
4. Start contributing!

**Comment by barkhaaroraa** [comment]
Hi could you assign me this issue under hacktober fest tag

**Comment by SRUJANA2199** [comment]
hi could you assign me this under hacktoberfest tag

**Comment by finn-str** [comment]
Hi, could you assign me this issue?

**Comment by parth-verma7** [comment]
Hi @Mrinank-Bhowmick I would like to work on this new Project. Please assign it to me.

**Comment by wilson-kong** [comment]
Hi, I would like to work on this project. Could you assign me this issue under hacktoberfest tag?

**Comment by Shashank-Shekharr** [comment]
hey , @Mrinank-Bhowmick  can u assign this to me please?

**Comment by anish2105** [comment]
Hey @Mrinank-Bhowmick , can you assign this to me?

**Comment by Mrinank-Bhowmick** [comment]
Hey 👋 @wilson-kong @Shashank-Shekharr @anish2105 @parth-verma7 @barkhaaroraa @SRUJANA2199 @finn-str 

As many of you are interested, I've kick-started a basic expense tracker project in the [expense-tracker](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Expense-Tracker) folder.
I encourage you all to add unique features to this project. 
Here's a brief description of each potential features that can be added:

1. **Expense Categorization**: This feature allows users to classify their expenses into categories like food, transportation, and entertainment, and provides a summary based on these categories.
2. **Date Range Filtering**: This feature enables users to filter and view their expenses within a specific date range.
3. **Expense Analysis**: This feature offers statistical insights such as the average expense, highest expense, lowest expense, etc.
4. **Data Saving and Loading**: This feature lets users save their expense data to a file (like CSV or JSON) and load it back when needed.
5. **Data Export to PDF/Excel**: This feature enables users to export their expense data to common formats like PDF or Excel for easy sharing or printing.
6. **Currency Converter**: For users dealing with multiple currencies, this feature provides an option to convert expenses to a preferred currency.
7. _Comment here if you want to add something else._
 
Contributors, please comment on the feature you're interested in working on, and I'll assign it accordingly. Your unique contributions will greatly enhance the functionality of this project!

**Comment by barkhaaroraa** [comment]
I’d like to work on the currency converter

**Comment by Shashank-Shekharr** [comment]
I would like to work on  Data Export to PDF/Excel.

**Comment by SRUJANA2199** [comment]
I would like to work on expense categorization

**Comment by Mrinank-Bhowmick** [comment]
@barkhaaroraa @Shashank-Shekharr 
Go for it ⚡ 
Just make sure to add changes in this [main.py](https://github.com/Mrinank-Bhowmick/python-beginner-projects/blob/main/projects/Expense-Tracker/main.py) file

**Comment by Rathish-Rajendran** [comment]
Hi @Mrinank-Bhowmick , I would like to implement the "Expense Analysis" part in the project. Can you kindly add my name to assignees?

**Comment by anish2105** [comment]
I would like to work on data range filtering

**Comment by anish2105** [comment]
Date of expense tracker is not being displayed in proper format , 
The input is in the correct format of (YYYY-MM-DD), but the view expense gives in the format of
ID: 1, Date: 2023-05-21-01, Description: shopping, Amount: Rs: 3000.0
where in Date: 2023-05-21-01 , -01 is extra

**Comment by Shashank-Shekharr** [comment]
At the function defination of add_expense ()
date = input().split()[0] + "-01"
remove  +"-01"
then it will be stored to correctly

**Comment by parth-verma7** [comment]
@Mrinank-Bhowmick @wilson-kong @Shashank-Shekharr @anish2105 @parth-verma7 @barkhaaroraa @SRUJANA2199 @finn-str  I am working on the Expense Analysis.
Thanks

**Comment by Rathish-Rajendran** [comment]
> @Mrinank-Bhowmick @wilson-kong @Shashank-Shekharr @anish2105 @barkhaaroraa @SRUJANA2199 @finn-str I am working on the Expense Analysis. Thanks

@parth-verma7 Hi, Kindly making you aware that I have already requested to work on the feature "Expense Analysis".

**Comment by Mrinank-Bhowmick** [comment]
Hey assigning you the issue for

@Rathish-Rajendran : Expense Analysis
@anish2105 : Date Range Filtering

@parth-verma7 please take some other as rathish is working on it 👍

**Comment by Shashank-Shekharr** [comment]
@Mrinank-Bhowmick   hey done Export to csv funtion and opened a pull request.

**Comment by anish2105** [comment]
@Mrinank-Bhowmick hey , done with data range filter please check it out.

**Comment by anish2105** [comment]
@Mrinank-Bhowmick , is any one doing data export to pdf?

**Comment by wilson-kong** [comment]
@anish2105 I think @Shashank-Shekharr is (https://github.com/Mrinank-Bhowmick/python-beginner-projects/issues/322#issuecomment-1740768344) 

@Mrinank-Bhowmick I would like to work on **4. Data Saving and Loading** if no one else is doing it.

**Comment by Shashank-Shekharr** [comment]
@anish2105  still working on pdf export sooner gonna roll it out .

**Comment by anish2105** [comment]
@Mrinank-Bhowmick , can merge my open request , I was assigned to data filter

**Comment by Mrinank-Bhowmick** [comment]
> @anish2105 I think @Shashank-Shekharr is ([#322 (comment)](https://github.com/Mrinank-Bhowmick/python-beginner-projects/issues/322#issuecomment-1740768344))
> 
> @Mrinank-Bhowmick I would like to work on **4. Data Saving and Loading** if no one else is doing it.

Gor for it

**Comment by Mrinank-Bhowmick** [comment]
Please in your PR mention this issue(with a #), so that it becomes easy to keep track

**Comment by anish2105** [comment]
> Please in your PR mention this issue(with a #), so that it becomes easy to keep track

@Mrinank-Bhowmick i have mentioned with a # , for data filter check it now

**Comment by Rathish-Rajendran** [comment]
Hi @Mrinank-Bhowmick , I have successfully implemented the expense analysis part and solved some minor bugs in the project. Kindly accept the pull request #441 and add "hacktoberfest-accepted" label. Thanks!

**Comment by Shashank-Shekharr** [comment]
hey , @Mrinank-Bhowmick   done pdf export and opened a pull request

**Comment by ca20110820** [comment]
Hello @Mrinank-Bhowmick , I am planning to add another mini-project to this repository, specifically a mini Computer Algebra System app. However, I am also interested in being assigned to and working on the Expense Tracker Project. Thank you!

**Comment by Mrinank-Bhowmick** [comment]
> Hello @Mrinank-Bhowmick , I am planning to add another mini-project to this repository, specifically a mini Computer Algebra System app. However, I am also interested in being assigned to and working on the Expense Tracker Project. Thank you!

go ahead

**Comment by Souravbudke** [comment]
Hey @Mrinank-Bhowmick , can you assign this to me?
