### ISSUE TITLE
Instagram Post Creation Project

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [Mrinank-Bhowmick/python-beginner-projects#323]
## Project Description 📄

We are looking for contributors who can help us build an **Instagram Post Creation** project using Python and libraries like Pillow. The goal of this project is to create a system that can generate Instagram posts. Like make basic templates so that users can use that.

## Getting Started 🚀

1. Fork this repository
2. Clone the forked repository
3. Set up your environment
4. Start contributing!

Please comment on this issue if you're interested in contributing or have any questions. Happy coding! 💻

**Comment by SamuraiPolix** [comment]
I would like to help :) I have a project on my profile where I generate quote images for Instagram/Pinterest using PILLOW - It can generate 100+ images in about 5 seconds!
[You can check it out here](https://github.com/SamuraiPolix/ImageQuoteGenerator)
Discord: s4murai.

**Comment by vagxrth** [comment]
Hey,  I'm excited about it, would it be possible to assign this issue to me? I believe it aligns well with my skills and interests, and I'd love to contribute further.

**Comment by Rathish-Rajendran** [comment]
Hi , I've taken a look at this project and I'm keen to contribute to this issue. With my experience in python, I'm confident I can provide a valuable solution. Please consider assigning this issue to me. Thanks!

**Comment by Mrinank-Bhowmick** [comment]
Hey 🤝 @SamuraiPolix @Rathish-Rajendran @vagxrth 

I'd like each of the three contributors to participate in this project. 
However, contributions should be placed in distinct folders within the [social_media_content_creation](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Social_media_content_creation) directory. 

Each should bring a unique approach to the project, or they can opt to modify or update the code of others.

**Comment by Mrinank-Bhowmick** [comment]
Any updates??

**Comment by dikshant182004** [comment]
hii @Mrinank-Bhowmick plz assign this issue to me

**Comment by Mrinank-Bhowmick** [comment]
> Hey 🤝 @SamuraiPolix @Rathish-Rajendran @vagxrth 
> 
> I'd like each of the three contributors to participate in this project. 
> However, contributions should be placed in distinct folders within the [social_media_content_creation](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Social_media_content_creation) directory. 
> 
> Each should bring a unique approach to the project, or they can opt to modify or update the code of others.

@dikshant182004 involving you also 🤝

**Comment by vagxrth** [comment]
@Mrinank-Bhowmick can you close this issue as the PR has been already merged
