### ISSUE TITLE
Updating contribution.md 

### ISSUE THREAD

**Issue by barkhaaroraa** [Mrinank-Bhowmick/python-beginner-projects#324]
**Is your feature request related to a problem? Please describe.**
Adding the code snippets and proper guidelines in the contribution.md file like how to fork and modify the repo on their own machine etc…

**Describe the solution you'd like**
For beginners i want to make the contribution.md file more informative with code snippets like how to add commit and push their respective code. 

**Describe alternatives you've considered**

**Additional context**

**Comment by th-shristi** [comment]
@barkhaaroraa contribution.md file already exist in this repo!

**Comment by barkhaaroraa** [comment]
right now it doesnt have detailed guidelines on how to run the repo/commit changes etc. i want to modify it and make it more detailed, something of this sort
<img width="315" alt="image" src="https://github.com/Mrinank-Bhowmick/python-beginner-projects/assets/115429121/41ef486b-3054-4e4c-aff5-287817e0ed6b">
<img width="418" alt="image" src="https://github.com/Mrinank-Bhowmick/python-beginner-projects/assets/115429121/921ac952-f3cd-45eb-a47f-25be96876077">
it is more detailed and beginner friendly

**Comment by th-shristi** [comment]
Anyone working on it or i can work on this issue?

**Comment by barkhaaroraa** [comment]
i'll start working on it once its assigned

**Comment by Mrinank-Bhowmick** [comment]
Sure go for it 🚀

**Comment by barkhaaroraa** [comment]
hi could you add the hacktober fest tag to this

**Comment by barkhaaroraa** [comment]
Hi I’ve made the necessary changes to the contribution.md file, could you please review it once and add hacktober fest tag to it

**Comment by Akarn-26** [comment]
Hi ! Since the contributing is not updated, shall I update it ?

**Comment by Akarn-26** [comment]
Hi @Mrinank-Bhowmick . I have just updated it. Please review it.

**Comment by Mrinank-Bhowmick** [comment]
> Hi @Mrinank-Bhowmick . I have just updated it. Please review it.

Mention pr link or number here

**Comment by Akarn-26** [comment]
#676
