### ISSUE TITLE
Movie Rater

### ISSUE THREAD

**Issue by Petsamuel** [Mrinank-Bhowmick/python-beginner-projects#326]
A simple python Api that handles movies and their respective ratings. These API can serve as a centralized hub for movie enthusiasts to share their opinions, discover new films, and assess the quality of movies they've watched.

**Comment by harshkasat** [comment]
Hi @Petsamuel, I have a suggestion. To make API calls more effective, we can integrate a KNN machine-learning model for movie recommendations and ratings. This way, we can receive personalized movie recommendations along with their ratings. Could you please assign me and label it as 'hacktoberfest'?

**Comment by Petsamuel** [comment]
Nice  idea, but I'm not the maintainer

**Comment by parth-verma7** [comment]
@Mrinank-Bhowmick I would like to work upon this issue. Can you please assign it to me.

**Comment by Mrinank-Bhowmick** [comment]
Hey @Petsamuel and @harshkasat ,
I want both of you to work on this issue together, just make sure you are adding your code in this folder -> [link](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/movie-rater)

**Comment by Mrinank-Bhowmick** [comment]
Hey @parth-verma7 , what features can you add to this

**Comment by ananyapillai72** [comment]
Hey! I would also like to contribute in it

**Comment by Mrinank-Bhowmick** [comment]
> Hey! I would also like to contribute in it

Hey what features can you add to this ?

**Comment by harshkasat** [comment]
Can I use RapidAPI's API to retrieve IMDb data and apply ML?

**Comment by Petsamuel** [comment]
@harshkasat I intended to create an API endpoint with Fastapi ... Considering what you just said now, how will the end product look like?

**Comment by harshkasat** [comment]
The IMDb API will provide us with 5 movie names with additional information: director, genre, and actor name. We can then input these five movie names and additional names into a KNN model to obtain recommendations for the closest matching movies.

**Comment by harshkasat** [comment]
I am considering creating a web application using the Django framework.

**Comment by Petsamuel** [comment]
nice. 
is there a platform we could use to work together on this ?

**Comment by harshkasat** [comment]
I am currently in the process of developing an ML model and have created an API and Django project using RapidAPI. However, being new to this, I am unsure of any platforms that could be used for collaboration on the project. Do you have any suggestions?😥😥

**Comment by Petsamuel** [comment]
We could use vscode live share

**Comment by harshkasat** [comment]
discord : zedmate

**Comment by Petsamuel** [comment]
kindly add bieefilled#0 I can't find your account.

**Comment by harshkasat** [comment]
@Petsamuel , it is now working. If it does not work, please provide me with your Discord username.

**Comment by harshkasat** [comment]
@Mrinank-Bhowmick Hi there, I created a PR two days ago. Could you please check it out? Thank you.

**Comment by Mrinank-Bhowmick** [comment]
Awesome Work @Petsamuel @harshkasat 🎉 
You may close this issue if it is done

**Comment by harshkasat** [comment]
@Petsamuel  Can you close this issue? Happy Hacking
