### ISSUE TITLE
Audio Captcha feature in Captcha_Generator.py

### ISSUE THREAD

**Issue by parth-verma7** [Mrinank-Bhowmick/python-beginner-projects#327]
In the Captcha Generator Project,
There is only text-image feature functionality.
Code for **Audio Captcha** can be included as a feature.

**Comment by parth-verma7** [comment]
> In the Captcha Generator Project, There is only text-image feature functionality. Code for **Audio Captcha** can be included as a feature.

@Mrinank-Bhowmick I would like to work upon this feature. Please assign it to me.

**Comment by Mrinank-Bhowmick** [comment]
Sure go for it 🚀

**Comment by parth-verma7** [comment]
> Sure go for it 🚀

@Mrinank-Bhowmick Please add the Hacktoberfest-23 fest as well.

**Comment by parth-verma7** [comment]
@Mrinank-Bhowmick I have submitted a PR, please look into it.

**Comment by Mrinank-Bhowmick** [comment]
I guess this issue is solved by your new pr , mention this issue by putting # in that pr
