### ISSUE TITLE
Want to add new Project under Hackoctoberfest

### ISSUE THREAD

**Issue by asingh4451** [Mrinank-Bhowmick/python-beginner-projects#336]
## Songs Mashup
A flask based web app that can produce mashup for mashup of any singer specified
@Mrinank-Bhowmick

**Comment by asingh4451** [comment]
@Mrinank-Bhowmick Kindly Allow me this under Hackoctober

**Comment by Mrinank-Bhowmick** [comment]
Looks interesting 👀 
Sure @asingh4451 go for it 🚀

**Comment by Mrinank-Bhowmick** [comment]
Merged #357
