### ISSUE TITLE
To add a Readme file for Hand Cricket Project 

### ISSUE THREAD

**Issue by ayan-joshi** [Mrinank-Bhowmick/python-beginner-projects#338]
**Is your feature request related to a problem? Please describe.**
Hand Cricket is a great python beginner project, it deserve a readme file to have a idea of it.

**Describe the solution you'd like**
I'll add a proper readme file for the project.

**Additional context**
Please assign me this issue under hacktoberfest label @Mrinank-Bhowmick , looking forward to get assigned.

**Comment by Dhandeep10** [comment]
As I completed the hand cricket game lastly, so @Mrinank-Bhowmick can you please assign me to this, so I can complete readme file for it.

**Comment by dikshant182004** [comment]
hii @Mrinank-Bhowmick plz assign this issue to me .so that i can contribute easily

**Comment by Mrinank-Bhowmick** [comment]
> As I completed the hand cricket game lastly, so @Mrinank-Bhowmick can you please assign me to this, so I can complete readme file for it.

PR is already merged can you check it once if there are any changes required
