### ISSUE TITLE
Madlibs generators.

### ISSUE THREAD

**Issue by hritikbhattacharya** [Mrinank-Bhowmick/python-beginner-projects#344]
The Mad Libs project in Python is a fun and interactive program that allows users to create humorous and often nonsensical stories by filling in the blanks with their own words or phrases. The project typically involves the following components:

Story Template: Start by creating a story template that includes a narrative with specific placeholders for different parts of speech (e.g., nouns, verbs, adjectives, adverbs).

User Input: Prompt the user to provide words or phrases for each placeholder. Collect and store these user inputs.

Story Generation: Replace the placeholders in the story template with the user-provided words or phrases, creating a customized and often comical story.

Display Story: Present the final generated story to the user, complete with their input, and let them enjoy the humorous results.

Repeat or Share: Optionally, allow the user to play again with a different template or share the generated story with others.

The Mad Libs project is a great way to practice user input, string manipulation, and basic Python programming concepts while providing an entertaining and creative experience for the users

**Comment by hritikbhattacharya** [comment]
assign this to me.

**Comment by hritikbhattacharya** [comment]
@Mrinank-Bhowmick  
Is there any issue with the idea?

**Comment by Mrinank-Bhowmick** [comment]
Hey @hritikbhattacharya 
Similar kind of project exist here -> https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Madlibs%20Generator

Try to make changes in that, assigning you this issue for the same

**Comment by hritikbhattacharya** [comment]
sorry I didn't looked that, sure
