### ISSUE TITLE
Feature Enhancement for Card game

### ISSUE THREAD

**Issue by ayan-joshi** [Mrinank-Bhowmick/python-beginner-projects#345]
**Is your feature request related to a problem? Please describe.**
Address Redundant Method and Attribute Names

**Describe the solution you'd like**
In the current codebase of the card game, there is a naming inconsistency that could lead to confusion. Specifically, the Game class has a method named wins, while the Player class also has an attribute with the same name, wins. This redundancy in naming might make it unclear whether we are referring to the method or the attribute when reading the code.

**Additional context**
Please assign me this issue under hackotoberfest label @Mrinank-Bhowmick

**Comment by Mrinank-Bhowmick** [comment]
Sure go for it 💯
