### ISSUE TITLE
Enhance Snake_Water_Gun_Game 

### ISSUE THREAD

**Issue by kom-senapati** [Mrinank-Bhowmick/python-beginner-projects#396]
File path: projects/snake_water_gun_game/Snake_Water_Gun_Game.py
I want to change the if-else ladder to nested if-else.
I want to change some variable names and change some print statements to make it more beautiful.

Also, I can use the rich library to make it more cool if you would like.

Please Assign me this issue under hacktoberfest.
Thanks in advance.

**Comment by Mrinank-Bhowmick** [comment]
Sure go for it

**Comment by abhayv290** [comment]
File path: projects/snake_water_gun_game/Snake_Water_Gun_Game.py

Hey this is Abhay can you please assign me this issue  I can be your best pick as I have solved leetcode que in python as also have star on hackerrank
I can code it in most efficient manner 

Feature I can added if i get this 
I can make it more easy to understand for other mean making code more readable
use ternary operators to do the job for more reliableless
and enhancing variable name to more understanding

**Comment by abhayv290** [comment]
Please check the PR  #529  I fixed it
