### ISSUE TITLE
Subtitle Synchronizer

### ISSUE THREAD

**Issue by glacias07** [Mrinank-Bhowmick/python-beginner-projects#41]
**Is your feature request related to a problem? Please describe.**
Subtitles we often download are out of sync because of different variation of a single movie of different lengths being out there. We often compensate for it by setting the offset via some video player like VLC. But every time we forward or try to rewind the movie it lags because it needs to again synchronize the subtitles.

**Describe the solution you'd like**
Using subtitle synchronizer, we can edit the time stamps of the srt file itself so the subtitles are perfectly aligned with the video.

**Describe alternatives you've considered**
I am using this program for the past 3 weeks and it is working perfectly so haven't really looked at any alternatives. Would love to have suggestions for other implementations though.

**Comment by Mrinank-Bhowmick** [comment]
Great program to make , go for it .
If you need any help mention me , I will contribute to it .
Assigning you this issue 👍

**Comment by glacias07** [comment]
@Mrinank-Bhowmick I have made the [PR #51](https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/51). Also currently we have to manually provide the shift. Any idea how we can completely automate it?

**Comment by Mrinank-Bhowmick** [comment]
> @Mrinank-Bhowmick I have made the [PR #51](https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/51). Also currently we have to manually provide the shift. Any idea how we can completely automate it?

I will review it and let you know
Thanks 👍

**Comment by glacias07** [comment]
> > @Mrinank-Bhowmick I have made the [PR #51](https://github.com/Mrinank-Bhowmick/python-beginner-projects/pull/51). Also currently we have to manually provide the shift. Any idea how we can completely automate it?
> 
> I will review it and let you know Thanks 👍

Great👍
