### ISSUE TITLE
Enhance Movie Recommendation system

### ISSUE THREAD

**Issue by breakthe-rule** [Mrinank-Bhowmick/python-beginner-projects#422]
File path: projects/Movie recommendation/movie_recommendation_engine.py

I am working an machine learning models for long time. Using this skill I may help you to upgrade this recommendation system to much higher level and with better recommendation

Please Assign me this issue under hacktoberfest.

**Comment by harshkasat** [comment]
This project is located in the folder projects\MovieApi_and_ML. It consists of a web application that retrieves movies from an API and provides recommendations based on them.
