### ISSUE TITLE
Enhancement of timer 

### ISSUE THREAD

**Issue by ayan-joshi** [Mrinank-Bhowmick/python-beginner-projects#444]
**Is your feature request related to a problem? Please describe.**
The timer python script is very basic I would like to enhance it and add some feature to it 

**Describe the solution you'd like**
The enhancement will be :

Encapsulated the timer logic in a function countdown_timer.
Added input validation to ensure the duration is a positive integer.
Improved user-friendly messages and error handling.
The timer can be stopped by the user with a KeyboardInterrupt (Ctrl+C).
Used a try...except block to catch and handle exceptions.

**Additional context**
Please assign me this issue under hacktobefest label @Mrinank-Bhowmick

**Comment by Mrinank-Bhowmick** [comment]
> **Is your feature request related to a problem? Please describe.** The timer python script is very basic I would like to enhance it and add some feature to it
> 
> **Describe the solution you'd like** The enhancement will be :
> 
> Encapsulated the timer logic in a function countdown_timer. Added input validation to ensure the duration is a positive integer. Improved user-friendly messages and error handling. The timer can be stopped by the user with a KeyboardInterrupt (Ctrl+C). Used a try...except block to catch and handle exceptions.
> 
> **Additional context** Please assign me this issue under hacktobefest label @Mrinank-Bhowmick

No more contributions under hacktoberfest label now, reopen this issue after October if you are really interested in open source contribution
