### ISSUE TITLE
Amazon product availability checker using Python

### ISSUE THREAD

**Issue by ayushi-ras** [Mrinank-Bhowmick/python-beginner-projects#454]
**Is your feature request related to a problem? Please describe.**

- **Personal Shopping:** Individuals may want to track the availability of products they intend to purchase when they become available.
- **Price Tracking**: Some users might be interested in knowing when a product becomes available at a lower price or during a sale.
- **Resale or Arbitrage:** Resellers or arbitrageurs may want to monitor the availability of certain products to buy and resell them when the prices increase or when they go out of stock.
- **Inventory Management:** Businesses might need to keep track of the availability of certain products for inventory management purposes.

**Describe the solution you'd like**
It checks the availability of a specific Amazon product and sends an email notification when the product becomes available

**Comment by ayushi-ras** [comment]
Please Assign me this @Mrinank-Bhowmick

**Comment by NitkarshChourasia** [comment]
You are assigned to it.
You don't ask repo owners, you just submit it through PR.
That's it.

**Comment by Mrinank-Bhowmick** [comment]
Merged 👍
