### ISSUE TITLE
Python Voice Assistant

### ISSUE THREAD

**Issue by Morbius00** [Mrinank-Bhowmick/python-beginner-projects#48]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

## Jarvis python voice assistant

* A simple python code voice assistant (Jarvis)
* user friendly 
* easy to access code

**Comment by Mrinank-Bhowmick** [comment]
Go for it 👍 
Assigning you this work 🚀

**Comment by Morbius00** [comment]
Hey Mrinank please add the Hacktoberfest22 label otherwise it will be accepted in hacktober fest

**Comment by Mrinank-Bhowmick** [comment]
Merged 
Happy Hacktoberfest 👍

**Comment by Morbius00** [comment]
Thanks for the merged...🤗
