### ISSUE TITLE
Add selection sort

### ISSUE THREAD

**Issue by MohitHire** [Mrinank-Bhowmick/python-beginner-projects#545]
hi, I want to add selection sort python program, please assign me this issue

**Comment by DevanshKyada27** [comment]
Hey @Mrinank-Bhowmick can you please assign this issue to me.
Want to contribute.

**Comment by DevanshKyada27** [comment]
Hey @Mrinank-Bhowmick @PythonicBoat can you please merge the PR.

**Comment by PythonicBoat** [comment]
@DevanshKyada27 Closing this issue, as we are not accepting algorithms as valid contributions, if you want to contribute to the repository try some mini projects which can be found at https://www.dataquest.io/blog/python-projects-for-beginners/
