### ISSUE TITLE
Enhance hangman gameplay

### ISSUE THREAD

**Issue by Limyangtyin** [Mrinank-Bhowmick/python-beginner-projects#626]
Implement different difficulty levels with varying word lengths or limited guesses to cater to different player skill levels.

**Comment by w3ngm0** [comment]
Please assign me this task. I will complete it! Thank you.

**Comment by SyedShagufta** [comment]
I have implemented this. could you please check my pull request?

Thank you.

**Comment by Mrinank-Bhowmick** [comment]
Closing if implemented or else mention PR number

**Comment by SyedShagufta** [comment]
Hello, 
I finished the task and submitted the changes as PR #641. However, I noticed that my changes weren't merged, and the issue was closed. I would really appreciate any feedback or guidance.
Thank you.
