### ISSUE TITLE
Missing Documentation in Calculator

### ISSUE THREAD

**Issue by sdthinlay** [Mrinank-Bhowmick/python-beginner-projects#644]
The Calculator lacks clear docstrings which are crucial for beginners to understand what the code does.

**Comment by abhijain1705** [comment]
hey, Can I work on this?

**Comment by LukeyTheFireCube** [comment]
Yo, just noticed this issue is still open, have there been any required documentation delivered in pull requests or whatnot? If not, I could try adding some if you want.
Lemme know if you're good with me acting on this issue.
Thanks!
