### ISSUE TITLE
Love calculator - reconstruct code structure, breakdown the code into function, include comments (user friendly and readability)

### ISSUE THREAD

**Issue by Limyangtyin** [Mrinank-Bhowmick/python-beginner-projects#653]
To reconstruct the code structure by breaking down into smaller function with meaningful names and make it more readability.

**Comment by ghraj2001** [comment]
hi, which python code are you asking about

**Comment by Mrinank-Bhowmick** [comment]
> To reconstruct the code structure by breaking down into smaller function with meaningful names and make it more readability.

Go for it

**Comment by ghraj2001** [comment]
yeah ,okay

**Comment by SarthakChaudhary46** [comment]
Hey!! There's no project by the name of "Love Calculator". 

Do you mean "Loan Calculator"?
