### ISSUE TITLE
Cannot access weather report on any major cities

### ISSUE THREAD

**Issue by Akarn-26** [Mrinank-Bhowmick/python-beginner-projects#669]
## Issue Summary

One cannot access the weather report on any major cities because of invalid cities format

## Description

I have identified an issue in the following code files:
-projects/API Based Weather Report/API Based Weather Report.py
-https://github.com/Mrinank-Bhowmick/python-beginner-projects/blob/98e7011347467853a14d003b207a0885709b5ce8/projects/API%20Based%20Weather%20Report/API%20Based%20Weather%20Report.py

The code simply does not run at all even for major cities like New Delhi, New York, Washington DC.......

**Comment by Mrinank-Bhowmick** [comment]
Looking for a new weather api

**Comment by Akarn-26** [comment]
would you like to view another weather project which does not depend on APIs but instead uses a python library. But it only shows weather report for The US....
