### ISSUE TITLE
Add validations to calendar code

### ISSUE THREAD

**Issue by smw-1211** [Mrinank-Bhowmick/python-beginner-projects#713]
While I was looking at calendar project, I found this is missing.

- Input passed by the user needs to be validated with certain validation checks.

- Ensure that the input entered at least is a month or a year.

**Comment by prathamesh19p** [comment]
Hey @Mrinank-Bhowmick, @smw-1211 
Can you assign this issue to me.

**Comment by smw-1211** [comment]
Sure. I would have surely if I was able to 😃.

@Mrinank-Bhowmick, I feel this should be noticed. Kindly assign this task to @prathamesh19p.

**Comment by Mrinank-Bhowmick** [comment]
Sure assigning the issue to you, mention this issue while creating a pr.
