### ISSUE TITLE
Email Client

### ISSUE THREAD

**Issue by zyetta** [Mrinank-Bhowmick/python-beginner-projects#85]
**Describe the solution you'd like**
Create a script that can send emails to a CSV list of recipients - Potential to customize names & custom attachments

**Additional context**
People often have to manually send out emails to people, containing the same information. E.g. invoicing, job applications, etc.
I want to make a script that reads fields like `email`, `first_name`, `last_name`, `attachment_dir` from a csv file, and automatically send emails from my entered address to the specified recipients.

**Comment by Mrinank-Bhowmick** [comment]
Great idea. Go for it 👍

**Comment by Josephtobi** [comment]
can multiple people be assigned to a project
this is my first time trying to contribute

**Comment by Mrinank-Bhowmick** [comment]
> can multiple people be assigned to a project this is my first time trying to contribute

@zyetta is in process
