### ISSUE TITLE
Adding a small game as a beginner friendly project

### ISSUE THREAD

**Issue by Yashparwal1** [Mrinank-Bhowmick/python-beginner-projects#98]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
I am adding another python beginner friendly project.
![swg_game](https://user-images.githubusercontent.com/54176283/194770566-90d5507c-a1ef-4f6e-a691-c9143eb9966c.png)

**Comment by Mrinank-Bhowmick** [comment]
Looks good
